<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\InventoryItem;
use App\Models\User;

class InventoryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@lab.com')->first();
        $userId = $adminUser ? $adminUser->id : 1;

        $inventoryItems = [
            // Reagents
            [
                'name' => 'Formalin 10%',
                'description' => 'Neutral buffered formalin for tissue fixation',
                'unit' => 'ml',
                'quantity' => 5000,
                'minimum_quantity' => 500,
                'unit_price' => 2.50,
                'supplier' => 'Sigma-Aldrich',
                'expiry_date' => now()->addMonths(12),
                'category' => 'reagents',
                'batch_number' => 'FA2025001',
                'lot_number' => 'LOT001',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'medium',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'Hematoxylin',
                'description' => 'Harris hematoxylin for nuclear staining',
                'unit' => 'ml',
                'quantity' => 1000,
                'minimum_quantity' => 100,
                'unit_price' => 15.00,
                'supplier' => 'Merck',
                'expiry_date' => now()->addMonths(18),
                'category' => 'reagents',
                'batch_number' => 'HX2025002',
                'lot_number' => 'LOT002',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'Eosin Y',
                'description' => 'Eosin Y solution for cytoplasmic staining',
                'unit' => 'ml',
                'quantity' => 800,
                'minimum_quantity' => 80,
                'unit_price' => 12.00,
                'supplier' => 'Sigma-Aldrich',
                'expiry_date' => now()->addMonths(24),
                'category' => 'reagents',
                'batch_number' => 'EY2025003',
                'lot_number' => 'LOT003',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],

            // Consumables
            [
                'name' => 'Microscope Slides',
                'description' => 'Pre-cleaned glass slides 25x75mm',
                'unit' => 'boxes',
                'quantity' => 50,
                'minimum_quantity' => 5,
                'unit_price' => 25.00,
                'supplier' => 'Thermo Fisher',
                'expiry_date' => null,
                'category' => 'consumables',
                'batch_number' => 'MS2025004',
                'lot_number' => 'LOT004',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'Cover Slips',
                'description' => 'Glass cover slips 22x22mm',
                'unit' => 'boxes',
                'quantity' => 30,
                'minimum_quantity' => 3,
                'unit_price' => 18.00,
                'supplier' => 'Thermo Fisher',
                'expiry_date' => null,
                'category' => 'consumables',
                'batch_number' => 'CS2025005',
                'lot_number' => 'LOT005',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'Paraffin Wax',
                'description' => 'High-grade paraffin wax for embedding',
                'unit' => 'kg',
                'quantity' => 25,
                'minimum_quantity' => 5,
                'unit_price' => 45.00,
                'supplier' => 'Leica Biosystems',
                'expiry_date' => null,
                'category' => 'consumables',
                'batch_number' => 'PW2025006',
                'lot_number' => 'LOT006',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],

            // Pathology specific
            [
                'name' => 'Ki-67 Antibody',
                'description' => 'Monoclonal antibody for Ki-67 proliferation marker',
                'unit' => 'ml',
                'quantity' => 10,
                'minimum_quantity' => 2,
                'unit_price' => 150.00,
                'supplier' => 'Dako',
                'expiry_date' => now()->addMonths(6),
                'category' => 'pathology',
                'batch_number' => 'KI2025007',
                'lot_number' => 'LOT007',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'medium',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'ER Antibody',
                'description' => 'Estrogen receptor monoclonal antibody',
                'unit' => 'ml',
                'quantity' => 8,
                'minimum_quantity' => 2,
                'unit_price' => 180.00,
                'supplier' => 'Dako',
                'expiry_date' => now()->addMonths(8),
                'category' => 'pathology',
                'batch_number' => 'ER2025008',
                'lot_number' => 'LOT008',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'medium',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],

            // Cytology specific
            [
                'name' => 'Pap Stain Kit',
                'description' => 'Papanicolaou staining kit for cytology',
                'unit' => 'kits',
                'quantity' => 15,
                'minimum_quantity' => 3,
                'unit_price' => 85.00,
                'supplier' => 'BD Biosciences',
                'expiry_date' => now()->addMonths(15),
                'category' => 'cytology',
                'batch_number' => 'PS2025009',
                'lot_number' => 'LOT009',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'Cytospin Funnels',
                'description' => 'Disposable cytospin funnels for cell preparation',
                'unit' => 'packs',
                'quantity' => 20,
                'minimum_quantity' => 4,
                'unit_price' => 35.00,
                'supplier' => 'Thermo Fisher',
                'expiry_date' => null,
                'category' => 'cytology',
                'batch_number' => 'CF2025010',
                'lot_number' => 'LOT010',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'low',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],

            // IHC specific
            [
                'name' => 'PD-L1 Antibody',
                'description' => 'Programmed death-ligand 1 antibody for IHC',
                'unit' => 'ml',
                'quantity' => 5,
                'minimum_quantity' => 1,
                'unit_price' => 220.00,
                'supplier' => 'Roche',
                'expiry_date' => now()->addMonths(4),
                'category' => 'ihc',
                'batch_number' => 'PD2025011',
                'lot_number' => 'LOT011',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'high',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],
            [
                'name' => 'DAB Substrate',
                'description' => '3,3\'-Diaminobenzidine substrate for IHC',
                'unit' => 'ml',
                'quantity' => 200,
                'minimum_quantity' => 50,
                'unit_price' => 8.50,
                'supplier' => 'Vector Labs',
                'expiry_date' => now()->addMonths(9),
                'category' => 'ihc',
                'batch_number' => 'DB2025012',
                'lot_number' => 'LOT012',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'critical',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],

            // Equipment
            [
                'name' => 'Microtome Blades',
                'description' => 'High-quality microtome blades for sectioning',
                'unit' => 'boxes',
                'quantity' => 12,
                'minimum_quantity' => 2,
                'unit_price' => 65.00,
                'supplier' => 'Leica Biosystems',
                'expiry_date' => null,
                'category' => 'equipment',
                'batch_number' => 'MB2025013',
                'lot_number' => 'LOT013',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'high',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],

            // Low stock items
            [
                'name' => 'Xylene',
                'description' => 'Xylene for tissue clearing',
                'unit' => 'ml',
                'quantity' => 200,
                'minimum_quantity' => 500,
                'unit_price' => 3.50,
                'supplier' => 'Sigma-Aldrich',
                'expiry_date' => now()->addMonths(36),
                'category' => 'reagents',
                'batch_number' => 'XY2025014',
                'lot_number' => 'LOT014',
                'storage_conditions' => 'Room temperature',
                'hazard_level' => 'high',
                'temperature_range' => '15-25°C',
                'updated_by' => $userId,
            ],

            // Expired item
            [
                'name' => 'Expired Antibody',
                'description' => 'Test antibody that has expired',
                'unit' => 'ml',
                'quantity' => 2,
                'minimum_quantity' => 1,
                'unit_price' => 100.00,
                'supplier' => 'Test Supplier',
                'expiry_date' => now()->subDays(30),
                'category' => 'pathology',
                'batch_number' => 'EX2025015',
                'lot_number' => 'LOT015',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'medium',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],

            // Expiring soon
            [
                'name' => 'Expiring Soon Reagent',
                'description' => 'Reagent expiring within 30 days',
                'unit' => 'ml',
                'quantity' => 100,
                'minimum_quantity' => 20,
                'unit_price' => 25.00,
                'supplier' => 'Test Supplier',
                'expiry_date' => now()->addDays(15),
                'category' => 'reagents',
                'batch_number' => 'ES2025016',
                'lot_number' => 'LOT016',
                'storage_conditions' => 'Refrigerated',
                'hazard_level' => 'low',
                'temperature_range' => '2-8°C',
                'updated_by' => $userId,
            ],
        ];

        foreach ($inventoryItems as $item) {
            InventoryItem::create($item);
        }
    }
}
